[package]
name = "axum-sdb-redis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.4"
redis = "0.22.3"
surrealdb = "1.0.0-beta.8"
